version: '3.1'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      volumes:
        - ./work/wwwroot:/etc/nginx/html/:rw
        - ./work/components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./work/components/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./work/components/nginx/log:/var/log/nginx:rw
      restart: always
      networks:
        - net-php73

  ### PHP container #########################################

  php73:
      build:
        context: ./build/php73
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
          DEV_MODE: ${GLOBAL_DEV_MODE}
      expose:
        - "${PHP_PORT}"
      volumes:
        - ./work/wwwroot:/etc/nginx/html:rw
        - ./work/components/php73/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./work/components/php73/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./work/components/php73/conf.d:/usr/local/etc/php/conf.d:rw
        - ./work/components/php73/log:/var/log:rw
        - ./work/components/php73/start.sh:/home/start.sh:rw
        - ./work/components/php73/backup:/backup:rw
        - ./work/components/php73/cron.d:/etc/cron.d:rw
      restart: always
      networks:
        - net-php73
        - net-db
        - net-redis

  ### Database container #########################################

  db:
      image: mariadb:10.4
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./work/components/mysql/data:/var/lib/mysql:rw
        - ./work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./work/components/mysql/log:/var/log/mysql:rw
      restart: always
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - net-db

  ### PhpMyAdmin container ####################################

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: ${PMA_ARBITRARY}
        PMA_HOST: db
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      restart: always
      ports:
        - "${PMA_PORT}:80"
      volumes:
        - ./work/components/phpmyadmin/sessions:/sessions:rw
      networks:
        - net-db

  ### Redis container #########################################

  redis:
      image: redis:5.0
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./work/components/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      networks:
        - net-redis

networks:
  net-php73:
  net-db:
  net-redis: